@startuml

[*] --> NoTask
NoTask --> TaskScheduled: SignalWorkflowExecution
TaskScheduled --> TaskStarted: StartTask
TaskScheduled --> TaskScheduled: SignalWorkflowExecution
TaskScheduled --> TaskFailed: stickiness timer
TaskStarted --> TaskCompleted: CompleteTask
TaskStarted --> TaskFailed: FailTask
TaskStarted --> TaskFailed: TimeoutTask
TaskStarted --> TaskStarted: SignalWorkflowExecution

TaskFailed --> TransientTaskScheduled: timer
TaskFailed --> TaskScheduled: failed because sticky ScheduleToStartTimeout

TaskCompleted --> TaskScheduled: Buffered Events
TaskCompleted --> NoTask

TransientTaskScheduled --> TransientTaskStarted: StartTask
TransientTaskScheduled --> TransientTaskScheduled: SignalWorkflowExecution

TransientTaskStarted --> TransientTaskFailed: FailTask
TransientTaskStarted --> TransientTaskCompleted: CompleteTask
TransientTaskStarted --> TransientTaskStarted: SignalWorkflowExecution

TransientTaskFailed --> TransientTaskScheduled

TransientTaskCompleted --> NoTask
TransientTaskCompleted --> TaskScheduled: Buffered Events

@enduml