@startuml

[*] --> NoTask
NoTask --> TaskScheduled: SignalWorkflowExecution
TaskScheduled --> TaskStarted: StartTask
TaskScheduled --> TaskScheduled: SignalWorkflowExecution
TaskScheduled --> TaskFailed: stickiness timer
TaskStarted --> TaskCompleted: CompleteTask
TaskStarted --> TaskFailed: FailTask
TaskStarted --> TaskFailed: TimeoutTask
TaskFailed --> TransientScheduled: timer
TaskFailed --> TaskScheduled: failed because sticky ScheduleToStartTimeout


   TransientScheduled --> TransientStarted: StartTask
   TransientStarted --> TransientTaskFailed: FailTask
   TransientTaskFailed --> TransientScheduled: timer
   TransientStarted --> TransientCompleted: CompleteTask
   TransientCompleted --> NoTask
   TaskCompleted --> TaskScheduled: Buffered Events
   TransientCompleted --> TaskScheduled: Buffered Events

TaskCompleted --> NoTask

@enduml